version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: lockfile-only
    groups:
      all-no-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
